name: Build application

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run py2app
      run: python3 setup.py py2app
    - name: Thin package
      run: |
        rm -rf dist/flux.app/Contents/Resources/lib/python3.8/PyQt5/Qt/lib/Qt{WebEngine,Designer,Quick}*
        rm -rf dist/Flux.app/Contents/Resources/lib/python3.8/PyQt5/Qt/qml/

